# image: python:3.9

cache:
  key: '$CI_COMMIT_REF_NAME'
  paths:
    - .venv/
    - __pycache__/

stages:
  - check
  - build
  - test
  - package
  - release
  - deploy

before_script:
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip install -U pip
  - pip install -r requirements.txt

lint:
  stage: check
  script:
    - pip install pylint
    - pylint --fail-under=4.0 apps/

build:
  stage: build
  script:
    - echo "No build step for Flask app"

test:
  stage: test
  script:
    - pip install pytest
    - pytest

package:
  stage: package
  script:
    - echo "No packaging step for Flask app"

release:
  stage: release
  script:
    - echo "No release step for Flask app"

deploy-dev:
  stage: deploy
  when: on_success
  resource_group: deployment
  variables:
    URL: '${CI_PROJECT_NAME}.bham.team'
    ACME: 'https://acme-staging-v02.api.letsencrypt.org/directory'
  before_script:
    - chmod 600 $RSA
    - source .venv/bin/activate
    - pip install -U pip
    - pip install -r requirements.txt
  script:
        # Now let's add code to run Flask over HTTPS
    - export FLASK_ENV=production
    - export FLASK_RUN_CERT=adhoc  # Use an ad-hoc SSL certificate for testing purposes
    - export FLASK_RUN_HOST=0.0.0.0
    - export FLASK_RUN_PORT=443  # Set Flask to listen on port 443 for HTTPS
    - nohup python3 run.py &
