image: python:3.9

cache:
  key: '$CI_COMMIT_REF_NAME'
  paths:
    - .venv/
    - __pycache__/

stages:
  - check
  - build
  - test
  - package
  - release
  - deploy

before_script:
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install -U pip
  - pip install -r requirements.txt

lint:
  stage: check
  script:
    - pip install pylint
    - pylint --fail-under=4.0 apps/

build:
  stage: build
  script:
    - echo "No build step for Flask app"

test:
  stage: test
  script:
    - pytest tests  # Run pytest to execute the tests

package:
  stage: package
  script:
    - echo "No packaging step for Flask app"

release:
  stage: release
  script:
    - echo "No release step for Flask app"

deploy-dev:
  image: python:3.9
  stage: deploy
  when: on_success
  script:
    - source .venv/bin/activate  # Activate the virtual environment
    - pip install -U pip
    - pip install -r requirements.txt
    # - docker-compose up -d
    # - docker system prune --force --filter 'until=24h'


# deploy-prod:
#   image: python:3.9
#   stage: deploy
#   when: on_success
#   only:
#     - tags
#   except:
#     - branches
#   dependencies:
#     - deploy-dev
#   resource_group: deployment
#   before_script:
#     - chmod og= $RSA
#     - apk update && apk add openssh-client sshpass
#   script:
#     - sshpass -Ppassphrase -p $PASSPHRASE ssh -o StrictHostKeyChecking=no -i $RSA $USER@$IP "cd ~/flask-app && docker-compose -f docker-compose.prod.yml up -d && docker system prune --force --filter 'until=24h'"
