# image: python:3.9

cache:
  key: '$CI_COMMIT_REF_NAME'
  paths:
    - .venv/
    - __pycache__/

stages:
  - check
  - build
  - test
  # - package
  # - release
  - deploy

before_script:
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip install -U pip
  - pip install -r requirements.txt

lint:
  stage: check
  script:
    - pip install pylint
    - pylint --fail-under=4.0 apps/

build:
  stage: build
  script:
    - sudo apt install -y default-jdk

test:
  stage: test
  script:
    - pip install pytest
    - pytest

# package:
#   stage: package
#   script:
#     - echo "No packaging step for Flask app"

# release:
#   stage: release
#   script:
#     - echo "No release step for Flask app"

deploy-dev:
  stage: deploy
  when: on_success
  tags:
    - dev
  resource_group: deployment
  variables:
    URL: '${CI_PROJECT_NAME}.bham.team'
    ACME: 'https://acme-staging-v02.api.letsencrypt.org/directory'
  before_script:
    - chmod 600 $RSA
    - source .venv/bin/activate
    - pip install -U pip
    - pip install -r requirements.txt
  script:
    - lsof -t -i :5000 | xargs kill -9 || true  # Kill processes listening on port 5000 if any, ignore errors
    - nohup python3 run.py > /dev/null 2>&1 &
    - exit 0

deploy-prod:
  stage: deploy
  when: on_success
  tags:
    - prod
  resource_group: deployment
  variables:
    URL: '${CI_PROJECT_NAME}.bham.team'
    ACME: 'https://acme-staging-v02.api.letsencrypt.org/directory'
  before_script:
    - chmod 600 $RSA
    - source .venv/bin/activate
    - pip install -U pip
    - pip install -r requirements.txt
  script:
    - lsof -t -i :5000 | xargs kill -9 || true  # Kill processes listening on port 5000 if any, ignore errors
    - nohup python3 run.py > /dev/null 2>&1 &
    - exit 0
