"""empty message

Revision ID: 027b60e7ca79
Revises: a564e9e5f762
Create Date: 2024-03-12 22:00:28.535870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027b60e7ca79'
down_revision = 'a564e9e5f762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('num',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.drop_column('progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), nullable=True))
        batch_op.alter_column('num',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    # ### end Alembic commands ###
