"""added events table

Revision ID: 0613a4133ba4
Revises: aae7207ae862
Create Date: 2024-03-15 16:32:56.123261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0613a4133ba4'
down_revision = 'aae7207ae862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.String(length=50), nullable=True))
        batch_op.drop_column('url')
        batch_op.drop_column('format_id')
        batch_op.drop_column('category_id')
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('format_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('url', sa.TEXT(), nullable=False))
        batch_op.drop_column('format')

    # ### end Alembic commands ###
