"""empty message

Revision ID: 1679fccf532e
Revises: 027b60e7ca79
Create Date: 2024-03-12 22:08:26.783644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1679fccf532e'
down_revision = '027b60e7ca79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('in_progress')
        batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(
        ), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('in_progress', sa.BOOLEAN(
        ), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
