"""empty message

Revision ID: 21da475b6037
Revises: ea7bbd709583
Create Date: 2024-03-19 13:41:42.136361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21da475b6037'
down_revision = 'ea7bbd709583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Profile')
    op.drop_table('Streak')
    op.drop_table('Points')
    op.drop_table('Follows')
    op.drop_table('Notifications')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('content_level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('expert_insights', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('content_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track', sa.String(length=50), nullable=True))
        batch_op.drop_column('progress')

    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('content_level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('content_level',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('track')

    with op.batch_alter_table('expert_insights', schema=None) as batch_op:
        batch_op.alter_column('content_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('content_level',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('Notifications',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=False),
    sa.Column('about_user', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('action', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['about_user'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Follows',
    sa.Column('follower_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('Points',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Streak',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('streak_start', sa.DATE(), nullable=True),
    sa.Column('streak_end', sa.DATE(), nullable=True),
    sa.Column('streak', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=True),
    sa.Column('bio', sa.INTEGER(), nullable=True),
    sa.Column('profile_picture', sa.BLOB(), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('last_online', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
