"""empty message

Revision ID: 2b4a73347885
Revises: bca6d56dafd3
Create Date: 2024-03-01 17:24:05.144916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4a73347885'
down_revision = 'bca6d56dafd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.Enum('beginner', 'intermediate',
                                            'advanced', name='difficultylevel'),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
                              existing_type=sa.Enum(
                                  'beginner', 'intermediate', 'advanced', name='difficultylevel'),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=False)

    # ### end Alembic commands ###
