"""empty message

Revision ID: 4aa678b6816c
Revises: 90fa611c0d85
Create Date: 2024-04-16 14:28:14.515836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa678b6816c'
down_revision = '90fa611c0d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Follows', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['id'])

    with op.batch_alter_table('Notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_', sa.Integer(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('type')

    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('content_level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False,
               existing_server_default=sa.text("'https://example.com/placeholder-image.jpg'"))

    with op.batch_alter_table('expert_insights', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('content_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False,
               existing_server_default=sa.text("'https://example.com/placeholder-image.jpg'"))

    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('resource_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('content_level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False,
               existing_server_default=sa.text("'https://example.com/placeholder-image.jpg'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'https://example.com/placeholder-image.jpg'"))
        batch_op.alter_column('content_level',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.alter_column('resource_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('expert_insights', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'https://example.com/placeholder-image.jpg'"))
        batch_op.alter_column('content_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'https://example.com/placeholder-image.jpg'"))
        batch_op.alter_column('content_level',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('Notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.INTEGER(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('type_')

    with op.batch_alter_table('Follows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['followed_id'], ['id'])
        batch_op.create_foreign_key(None, 'Users', ['follower_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
