"""empty message

Revision ID: 8226038c1223
Revises: 0613a4133ba4
Create Date: 2024-03-16 22:56:12.106975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8226038c1223'
down_revision = '0613a4133ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lesson_id', sa.Integer(), nullable=False),
                    sa.Column('image_path', sa.String(
                        length=255), nullable=False),
                    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('Follows')
    op.drop_table('Streak')
    op.drop_table('Notifications')
    op.drop_table('Points')
    op.drop_table('Profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profile',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('full_name', sa.TEXT(), nullable=True),
                    sa.Column('bio', sa.INTEGER(), nullable=True),
                    sa.Column('profile_picture', sa.BLOB(), nullable=True),
                    sa.Column('location', sa.TEXT(), nullable=True),
                    sa.Column('last_online', sa.DATETIME(), server_default=sa.text(
                        '(CURRENT_TIMESTAMP)'), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Points',
                    sa.Column('id', sa.INTEGER(), nullable=True),
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('points', sa.INTEGER(), nullable=True),
                    sa.Column('date', sa.DATE(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Notifications',
                    sa.Column('id', sa.INTEGER(), nullable=True),
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('type', sa.INTEGER(), nullable=False),
                    sa.Column('about_user', sa.INTEGER(), nullable=True),
                    sa.Column('content', sa.TEXT(), nullable=False),
                    sa.Column('action', sa.TEXT(), nullable=True),
                    sa.Column('created_at', sa.DATETIME(), server_default=sa.text(
                        '(CURRENT_TIMESTAMP)'), nullable=True),
                    sa.ForeignKeyConstraint(['about_user'], ['Users.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Streak',
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('streak_start', sa.DATE(), nullable=True),
                    sa.Column('streak_end', sa.DATE(), nullable=True),
                    sa.Column('streak', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_table('Follows',
                    sa.Column('follower_id', sa.INTEGER(), nullable=False),
                    sa.Column('followed_id', sa.INTEGER(), nullable=False),
                    sa.ForeignKeyConstraint(['followed_id'], ['Users.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
                    )
    op.drop_table('lesson_images')
    # ### end Alembic commands ###
