"""empty message

Revision ID: a5c132b56d39
Revises: 7aca60451abb
Create Date: 2024-03-17 03:14:50.811137

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5c132b56d39"
down_revision = "7aca60451abb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('Profile')
    # op.drop_table('Follows')
    op.drop_table("user-data")
    # op.drop_table('Notifications')
    # op.drop_table('Points')
    # op.drop_table('Streak')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Streak",
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("streak_start", sa.DATE(), nullable=True),
        sa.Column("streak_end", sa.DATE(), nullable=True),
        sa.Column("streak", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "Points",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("points", sa.INTEGER(), nullable=True),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Notifications",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("type", sa.INTEGER(), nullable=False),
        sa.Column("about_user", sa.INTEGER(), nullable=True),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("action", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["about_user"],
            ["Users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user-data",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("lessons_completed", sa.INTEGER(), nullable=True),
        sa.Column("lessons_in_progress", sa.INTEGER(), nullable=True),
        sa.Column("streak", sa.INTEGER(), nullable=True),
        sa.Column("user_level", sa.TEXT(), nullable=False),
        sa.Column("progress_to_next_level", sa.FLOAT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Follows",
        sa.Column("follower_id", sa.INTEGER(), nullable=False),
        sa.Column("followed_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["followed_id"],
            ["Users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("follower_id", "followed_id"),
    )
    op.create_table(
        "Profile",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("full_name", sa.TEXT(), nullable=True),
        sa.Column("bio", sa.INTEGER(), nullable=True),
        sa.Column("profile_picture", sa.BLOB(), nullable=True),
        sa.Column("location", sa.TEXT(), nullable=True),
        sa.Column(
            "last_online",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
