"""empty message

Revision ID: aae7207ae862
Revises: c625b30f2bc2
Create Date: 2024-03-15 09:42:58.805364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae7207ae862'
down_revision = 'c625b30f2bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column(
        'order_in_lesson', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'order_in_lesson')
    # ### end Alembic commands ###
