"""empty message

Revision ID: bca6d56dafd3
Revises: cd091919d98c
Create Date: 2024-03-01 16:25:11.151239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca6d56dafd3'
down_revision = 'cd091919d98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        # Step 1: Add the column as nullable
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))

    # Step 2: Populate the column for existing rows
    # Assuming 'beginner' as the default value for the sake of this example
    op.execute('UPDATE lessons SET difficulty = \'beginner\' WHERE difficulty IS NULL')

    # Step 3: Alter the column to be non-nullable
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('difficulty', nullable=False)
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
