"""empty message

Revision ID: c625b30f2bc2
Revises: 1679fccf532e
Create Date: 2024-03-13 17:10:08.563517

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c625b30f2bc2"
down_revision = "1679fccf532e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=150), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("start_utc", sa.DateTime(), nullable=False),
        sa.Column("end_utc", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("online_event", sa.Boolean(), nullable=False),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("category_id", sa.String(length=50), nullable=True),
        sa.Column("format_id", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###
