"""empty message

Revision ID: cd091919d98c
Revises: 
Create Date: 2024-02-29 22:30:00.245135

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd091919d98c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "in_progress",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.false_(),
            )
        )
        batch_op.add_column(sa.Column("last_accessed", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("progress", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "completed",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.false_(),
            )
        )

    # After adding columns, update them to be NOT NULL as intended
    op.execute("UPDATE lessons SET in_progress = 0 WHERE in_progress IS NULL")
    op.execute("UPDATE lessons SET completed = 0 WHERE completed IS NULL")

    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.alter_column("in_progress", existing_type=sa.Boolean(), nullable=False)
        batch_op.alter_column("completed", existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.drop_column("completed")
        batch_op.drop_column("progress")
        batch_op.drop_column("last_accessed")
        batch_op.drop_column("in_progress")

    # ### end Alembic commands ###
