"""empty message

Revision ID: dc2fd70dc1af
Revises: de7ab20987af
Create Date: 2024-03-07 13:22:13.701925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2fd70dc1af'
down_revision = 'de7ab20987af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'num')
    # ### end Alembic commands ###
