"""empty message

Revision ID: ddba02e0215c
Revises: dc2fd70dc1af
Create Date: 2024-03-08 13:34:46.767436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddba02e0215c'
down_revision = 'dc2fd70dc1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('oauth_github')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('oauth_github', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
