"""empty message

Revision ID: de7ab20987af
Revises: 2b4a73347885
Create Date: 2024-03-04 23:44:23.867217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'de7ab20987af'
down_revision = '2b4a73347885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('scenario_details', sa.Text(), nullable=True))
        batch_op.alter_column('expected_sentiments',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.drop_column('title')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=150), nullable=False))
        batch_op.alter_column('expected_sentiments',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.drop_column('scenario_details')
        batch_op.drop_column('scenario_name')

    # ### end Alembic commands ###
